# Assignment 1: Data Cleaning (Gender Column)
This notebook loads the reduced Emergency Triage dataset. It deals with missing values in the "Gender" column by dropping their corresponding rows. Additionally, it maps the different unique values of the "Gender" column to two values: `1` (Male) and `0` (Female).

In [45]:
# Confirm Python version >= 3.10
import sys
print(f'Python version: {sys.version}')

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [46]:
# Import necessary libraries
import pandas as pd
import numpy as np

print('Libraries imported successfully!')

Libraries imported successfully!

In [47]:
# Load dataset and display shape & column names
FILE_PATH = 'EmergencyTriageDataset_Reduced_Dirty.csv'
df_raw = pd.read_csv(FILE_PATH)

print('Dataset successfully loaded!')
print(f'Shape: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns')
print(f'Columns: {list(df_raw.columns)}')

Dataset successfully loaded!
Shape: 2205 rows x 11 columns
Columns: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [48]:
# Display first 10 rows
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [49]:
# Display the data types of each column
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [50]:
# Check for any missing values in the 'Gender' column
print(f'Number of NaN values in "Gender": {df_raw['Gender'].isnull().sum()}')

Number of NaN values in "Gender": 0

**Note:** No cases of missing values in the "Gender" column so no action is required to rectify this

In [51]:
# Drop rows with NaN value
df_raw = df_raw.dropna(subset=['Gender'])

In [52]:
# Display all the unique values in the 'Gender' column
print(f'Unique values in "Gender": {df_raw['Gender'].unique()}')
print(f'Number of unique values in "Gender": {df_raw['Gender'].nunique()}')

Unique values in "Gender": ['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']
Number of unique values in "Gender": 6

In [53]:
# Display 'Gender' value counts
print(f'Gender value counts: {df_raw['Gender'].value_counts()}')

Gender value counts: Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [54]:
# Build value map
gender_map = {
    'male': 1,
    '1': 1,
    'female': 0,
    '0': 0
}

In [55]:
# Normalize all values to lower case
df_raw['Gender_Cleaned'] = df_raw['Gender'].astype(str).str.lower().str.strip().map(gender_map)

In [56]:
# Display value counts for new columns
print(f'Cleaned "Gender" value counts: {df_raw['Gender_Cleaned'].value_counts()}')

Cleaned "Gender" value counts: Gender_Cleaned
1    1176
0    1029
Name: count, dtype: int64

In [57]:
# Check for null values in the cleaned column
print(f'Number of NaN values in "Gender": {df_raw['Gender_Cleaned'].isnull().sum()}')

Number of NaN values in "Gender": 0

In [58]:
# Drop old "Gender" column and rename cleaned column
df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_Cleaned': 'Gender'})

df_raw.head(10)

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0
5   6   42  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0       1
6   7   75  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0       0
7   8   25  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0       1
8   9   67  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0       0
9  11   82  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0       0